version: '3.2'
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - streammon_pg_data:/var/lib/postgresql/data/

  monitor:
    image: "dreamworkerln/streammonitoring-monitor"
    environment:
      spring_profiles_active: 
    restart: always
    volumes:
      - type: bind
        source: ./monitor/application.properties
        target: /application.properties
      - type: bind
        source: ./monitor/monitor.properties
        target: /monitor.properties
    ports:
      - 8015:8015


  tbot:
    image: "dreamworkerln/streammonitoring-tbot"
    depends_on:
      - monitor
    environment:
      spring_profiles_active: 
    restart: always
    volumes:
      - type: bind
        source: ./tbot/application.properties
        target: /application.properties
      - type: bind
        source: ./tbot/tbot.properties
        target: /tbot.properties

volumes:
  streammon_pg_data:
