version: '3.2'
services:
  monitor:
    image: "dreamworkerln/streammonitoring-monitor"
    environment:
      SPRING_APPLICATION_JSON: '{
        "logging.level.ru.kvanttelecom.tv.streammonitoring": "INFO",
        "server.port": "8015",
        "client.protocol" :"http://",
        "refresh.interval.sec": "10",
        "check.stream.uniqueness": "true",
        "media.server.list": "video1.streamer.ru,video2.streamer.ru,video3.streamer.ru",
        "media.server.username": "USERNAME",
        "media.server.password": "PASSWORD"
      }'
    restart: always

  tbot:
    image: "dreamworkerln/streammonitoring-tbot"
    depends_on:
      - monitor
    environment:
      SPRING_APPLICATION_JSON: '{
        "logging.level.ru.kvanttelecom.tv.streammonitoring": "DEBUG",
        "server.port": "8075",
        "client.protocol" :"http://",
        "telegram.bot.token": "TOKEN",
        "telegram.bot.group": "GROUP_ID"
      }'
    restart: always
