version: '3.2'
services:
  monitor:
    image: "dreamworkerln/streammonitoring-monitor"
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port": "80",
        "logging.level.ru.kvanttelecom.tv.streammonitoring": "INFO",
        "bot.url": "bot",
        "delay.threshold.sec": "100",
        "refresh.interval.sec": "10",
        "media.server.list": "video1.streamer.ru,video2.streamer.ru,video3.streamer.ru",
        "media.server.username": "USERNAME",
        "media.server.password": "PASSWORD"
      }'
    restart: always

  tbot:
    image: "dreamworkerln/streammonitoring-tbot"
    depends_on:
      - monitor
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port": "80",
        "logging.level.ru.kvanttelecom.tv.streammonitoring": "DEBUG",
        "monitor.url": "monitor"
      }'
    restart: always
